version: "3.9"

services:
  battlesnake:
    image: sendwithus/battlesnake-server
    ports:
      - "3000:3000"

  zsnake-java:
    build:
      context: .
      dockerfile: ./teams/znake-starter-springboot/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - battlesnake

  zsnake-node:
    build:
      context: ./teams/znake-starter-node
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - battlesnake

  zsnake-go:
    build:
      context: ./teams/znake-starter-go
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - battlesnake